apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions
  labels:
    app: actions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: actions
  template:
    metadata:
      labels:
        app: actions
    spec:
      containers:
        - name: actions
          image: mrspock182/actions:latest
          ports:
            - containerPort: 8080
              protocol: TCP