name: Deploy Application
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Maven Build
        run: mvn -N wrapper:wrapper
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login Dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build docker image
        run: docker build -t mrspock182/actions .
      - name: Push image docker
        run: docker push mrspock182/actions