name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login Dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build docker image
        run: docker build -t mrspock182/actions .
      - name: Push image docker
        run: docker push mrspock182/actions

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull mrspock182/actions:latest
      - name: Remove docker container
        run: docker rm -f actions
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e APP_NAME='${{secrets.APP_NAME}}' --name actions mrspock182/actions